package com.app.Enum;

public enum EventType {
	
	TRIP_STARTED,
	PICKUP_FROM_PARENT,
    DROP_TO_SCHOOL,
    PICKUP_FROM_SCHOOL,
    DROP_TO_PARENT,
    GATE_ENTRY,
    GATE_EXIT,
    ARRIVAL_NOTIFICATION,
    PICKUP_CONFIRMATION,
    DROP_CONFIRMATION,
    DELAY_NOTIFICATION
    

}
