package com.app.Enum;

public enum NotificationType {
	SMS, 
	PUSH, 
	EMAIL,
	ARRIVAL_NOTIFICATION,
	PICKUP_CONFIRMATION,
	DROP_CONFIRMATION,
	DELAY_NOTIFICATION,
	TRIP_UPDATE,
	ATTENDANCE_UPDATE,
	SYSTEM_ALERT
}
